#!/bin/sh
# MUST BE RUN AS ROOT

# Replace default libre repository with your own if desired
url=https://ymirlinux.org/libre

# Replace with whatever 5.x kernel you wish to install
kern=5.8

# install libre base-system with linux-libre and remove evil nonfree kernel and blobs
echo "repository=$url" > /etc/xbps.d/40-ymir-repo-libre.conf
xbps-install -Sf base-system base-files && xbps-remove linux $(xbps-query --regex -s '^linux[0-9.]+-[0-9._]+' | awk '{print $2}') linux-firmware linux-firmware-amd linux-firmware-intel linux-firmware-network linux-firmware-nvidia

# remove old kernels from /boot
vkpurge rm all

# Option to install your-freedom package to ensure the installation of only libre sotware
while true; do
	echo -n "Install your-freedom to conflict with all nonfree or semi-free packages and install liberated versions of conflicting packages where possible? (y/n) "
	read ans3
	case $ans3 in
		[Yy]* ) for package in $(curl https://github.com/ymir-linux/void-packages/blob/master/srcpkgs/your-freedom/allowlist.txt | cut -f1 -d':')
	    		do xbps-install -Sf $package; done && xbps-install -Sf your-freedom; break;;
		[Nn]* ) exit;;
		* ) echo "Please answer yes or no.";;
    	esac
done
