#!/bin/sh
# This is a script I wrote to automate the somewhat annoying process of migrating a Void Linux installation out of the Void and into the light of Linux-libre.
# I wrote this script for me, I can't guarantee this will work on your system.
# make sure you have xtools and fzf installed.

# check if "xtools" and "fzf" are installed and install them if they are not
[ -z $(command -v xi) ] && sudo xbps-install -S xtools
[ -z $(command -v fzf) ] && sudo xbps-install -S fzf

# set up the void-packages repo
while true; do
	echo -n "Install void-packages in ~/.local/src or in current directory? (y/n)"
	read ans
	case $yn in
       		[Yy]* ) srcdir="~/.local/src"; break;;
		[Nn]* ) srcdir=$(pwd); break;;
        	* ) echo "Please answer yes or no.";;
    	esac
done
cd $srcdir || mkdir $srcdir

git clone --depth 1 https://github.com/ymir-linux/void-packages.git
cd void-packages
./xbps-src binary-bootstrap

# install linux-libre
cd srcpkgs
vrs=$(ls | grep "linux-libre...$" | fzf -i --prompt="Kernel version:")
[ -z $vrs ] && exit
cd ..
./xbps-src pkg $vrs
xi $vrs

# remove evil nonfree kernel and blobs
sudo xbps-remove linux $(xbps-query --regex -s '^linux[0-9.]+-[0-9._]+' | awk '{print $2}') linux-firmware-amd linux-firmware-intel linux-firmware-network linux-firmware-nvidia

# remove old kernels from /boot
sudo vkpurge rm all

# Optionally install vkpurge alternative
while true; do
	echo -n "Install vkpurge-libre (linux-libre compatible vkpurge tool)? (y/n)"
	read ans2
	case $yn in
       		[Yy]* ) sudo cp $srcdir/void-packages/vkpurge-libre /usr/bin; break;;
        	[Nn]* ) break;;
        	* ) echo "Please answer yes or no.";;
    	esac
done

# OPTIONAL: install Parabola's your-freedom package (conflicts with both nonfree and semi-free packages, so it may not work for you)
while true; do
	echo -n "Install your-freedom to conflict with all nonfree or semi-free packages and install liberated versions of conflicting packages where possible? (y/n) "
	read ans3
	case $ans3 in
		[Yy]* ) for package in $(curl https://github.com/ymir-linux/void-packages/blob/master/srcpkgs/your-freedom/allowlist.txt | cut -f1 -d':')
	    		do ./xbps-src pkg $package; done; ./xbps-src pkg your-freedom; break;;
		[Nn]* ) exit;;
		* ) echo "Please answer yes or no.";;
    	esac
done
