#!/bin/sh
# MUST BE RUN AS ROOT

# Replace default libre repository with your own if desired
url=http://198.255.68.182/libre

# Replace with whatever 5.x kernel you wish to install
kern=5.8

# install libre base-system with linux-libre
xbps-install -Sf base-system base-files

# remove evil nonfree kernel and blobs
xbps-remove linux $(xbps-query --regex -s '^linux[0-9.]+-[0-9._]+' | awk '{print $2}') linux-firmware linux-firmware-amd linux-firmware-intel linux-firmware-network linux-firmware-nvidia

# remove old kernels from /boot
vkpurge rm all

# Option to install your-freedom package to ensure the installation of only libre sotware
echo -n "Install your-freedom to conflict with all nonfree or semi-free packages and install liberated versions of conflicting packages where possible? "
read ans3
if [ "$ans3" != "${answer#[Yy]}" ]; then
	for package in $(cat srcpkgs/allowlist.txt); do
		xbps-install -S $package
	done
	xbps-install -S your-freedom
fi
