#!/bin/sh
# This is a script I wrote to automate the somewhat long process of migrating a Void Linux installation out of the Void and into the Light of Linux-libre.
# I wrote this script for me, I can't guarantee this will work on your system.
# Before you run this in your home directory, either mkdir ~/.local/src or comment out the first line.
# if you have already cloned the void-packages repo, comment the relevant line out.

# set up the void-packages repo
cd ~/.local/src
git clone https://github.com/drake-newell/void-packages.git
cd void-packages
./xbps-src binary-bootstrap

# install linux-libre
cd srcpkgs
vrs=$(ls | grep "linux-libre" | grep -Ev 'dbg|headers' | dmenu -i -p "Kernel version:")
cd ..
./xbps-src pkg $vrs
xi $vrs

# remove base-system to eliminate dependency on evil nonfree kernel and blobs
sudo xbps-remove base-system
sudo xbps-install base-voidstrap

# remove evil nonfree kernel and blobs
sudo xbps-remove $(cd srcpkgs && ls | grep linux'[[:digit:]]' | grep -Ev 'dbg|headers' | dmenu -i -p "Remove kernel:")
sudo xbps-remove linux-firmware linux-firmware-amd linux-firmware-dvb linux-firmware-intel linux-firmware-network linux-firmware nvidia
